platform :ios, '13.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'ForYouAndMe_Example' do
  pod 'ForYouAndMe', :path => '../', :inhibit_warnings => false
  
  target 'ForYouAndMe_Tests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'SwiftLint', '0.42.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['ForYouAndMe'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) HEALTHKIT'
      end
    end
    target.build_configurations.each do |config|
      # Fix forced pod signing issue on azure
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      # Clear the deployment target warning
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
