disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - type_body_length

line_length: 140

variable_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
