# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- CI_CD

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
    projectDirectory: '$(Build.SourcesDirectory)/ForYouAndMe/Example'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'GoogleService-Info.plist'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'GoogleService-Info.plist'
    TargetFolder: '$(system.defaultWorkingDirectory)/ForYouAndMe/Example/ForYouAndMe'
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '$(Build.SourcesDirectory)/ForYouAndMe/Example/ForYouAndMe.xcworkspace'
    scheme: 'ForYouAndMe-Example'
    packageApp: true
- task: CopyFiles@2
  inputs:
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1
